### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by nibo**
I did some fixes which caused errors in my code. As well i did some modification to modify the scroll and reorder animation speed

### CODE REVIEW

**Comment by RaviKavaiya** [comment]
@nibo  Can you please send some screenshots regarding changes you made? It may make easy for the owner to review...

**Comment by nibo** [comment]
> @nibo Can you please send some screenshots regarding changes you made? It may make easy for the owner to review...

I did not much, but it causes less problems with scrollcontroller in **reorderable_flex.dart**:

Bildschirmfoto 2020-08-10 um 07 06 29


Bildschirmfoto 2020-08-10 um 06 55 48

Bildschirmfoto 2020-08-10 um 07 03 44

I have also parameterized the duration of the animation for scroll and reorder in **reorderable_flex.dart and reorderable_wrap:
.dart**

Bildschirmfoto 2020-08-10 um 06 57 50

Bildschirmfoto 2020-08-10 um 06 58 38

Bildschirmfoto 2020-08-10 um 06 59 28

Bildschirmfoto 2020-08-10 um 07 15 12

**Comment by nibo** [comment]
I did some additional changes in flex & wrap which makes it possible to use them inside parent Widgtes with ScrollControllers. So you can add the ScrollController to parent ScrollView pass it through to "flex" or "wrap" an the whole Screen will Scroll while sorting(as example CustomScrollView with SliverList)


Bildschirmfoto 2020-08-12 um 13 42 12
Bildschirmfoto 2020-08-12 um 13 46 11

**Comment by RaviKavaiya** [comment]
@nibo you are doing good job. Nice of you. But, I don't think the repo owner is currently having time :( 
You can see that there is no commit in the repo since 5 months.

This package is great.
Let's depend on time...

**Comment by hanshengchiu** [comment]
@nibo @RaviKavaiya 
Would like to invite you as collaborator..

**Comment by RaviKavaiya** [comment]
@hanshengchiu Thank you for inviting me.
But, currently I am too much busy to focus on this package. Sorry.

I would let you know once I get time and I would be happy to collaborate then.

Thanks.

**Pull request merged**
