### PR TITLE
Null safety release cleanup

### PR DESCRIPTION
**Pull request by diegotori**
Addresses #110. Once you approve, do not merge just yet. I need to update the version name and changelog. Then you can merge, and then I'll kickoff a new pub.dev release.

### CODE REVIEW

**Comment by ericmartineau** [comment]
I released this branch as `reorderables2` until the author makes a formal null-safe release.

**Comment by diegotori** [comment]
@hanshengchiu a gentle reminder regarding this PR. Thanks in advance.

**Comment by bdlukaa** [comment]
This would be great!

**Comment by diegotori** [comment]
@hanshengchiu Updated the version, and published `0.4.0` to pub.dev.

**Pull request merged**
