### PR TITLE
Fix crashes when using Flutter 3.7

### LINKED ISSUE #167: PrimaryScrollController.of() was called with a context that does not contain a PrimaryScrollController widget thrown after flutter upgrade
Hi,
I've just upgraded to Flutter 3.6.0-4.0.pre.2 • channel master
After upgrade I get this message:
`I/flutter ( 8048):   _ReorderableFlexContent(dirty, dependencies: [PrimaryScrollController], state:
I/flutter ( 8048): _ReorderableFlexContentState#46973(tickers: tracking 2 tickers))
I/flutter ( 8048): 
I/flutter ( 8048): The relevant error-causing widget was:
I/flutter ( 8048):   _ReorderableFlexContent
I/flutter ( 8048):   _ReorderableFlexContent:file:///C:/Users/oreznik/AppData/Local/Pub/Cache/hosted/pub.dev/reorderables-0.5.1/lib/src/widgets/reorderable_flex.dart:139:16
I/flutter ( 8048): 
I/flutter ( 8048): When the exception was thrown, this was the stack:
I/flutter ( 8048): #0      PrimaryScrollController.of.<anonymous closure> (package:flutter/src/widgets/primary_scroll_controller.dart:158:9)
I/flutter ( 8048): #1      PrimaryScrollController.of (package:flutter/src/widgets/primary_scroll_controller.dart:170:6)
I/flutter ( 8048): #2      _ReorderableFlexContentState.build (package:reorderables/src/widgets/reorderable_flex.dart:885:33)`

I was using   reorderables: ^0.5.1 and ^0.5.0
flutter doctor is fine
This is my code:

`final ScrollController reorderScrollController = ScrollController();
List<Widget> _row=[....];
  @override
  Widget build(BuildContext context) {
 return ReorderableColumn(
      children: _rows,
      onReorder: _onReorder,
//Error is not changed if I add this parameter
      scrollController: reorderScrollController ,
    );
}`

### PR DESCRIPTION
**Pull request by luccasclezar**
Fixes #167 PrimaryScrollController.of() was called with a context that does not contain a PrimaryScrollController widget thrown after flutter upgrade

### CODE REVIEW

**Comment by diegotori** [comment]
LGTM.

**Comment by diegotori** [comment]
@luccasclezar is there any chance that you can revert the formatting changes until I establish proper Dart linting on this project?

Thanks in advance.

**Comment by luccasclezar** [comment]
Sure, I didn't mean to format that 😅

**Comment by diegotori** [comment]
No worries.

**Comment by luccasclezar** [comment]
Done

**Comment by diegotori** [comment]
I'll merge this first thing in the morning, since it's getting late.

**Pull request merged**
